name: quizapp
description: Flutter Quiz App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  audioplayers: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sfx/


  fonts:
    - family: Die
      fonts:
        - asset: assets/fonts/DIEDIEDI.ttf
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
    - family: Sketchzone
      fonts:
        - asset: assets/fonts/Sketchzone.otf
    - family: KGB
      fonts:
        - asset: assets/fonts/KGBlankSpaceSketch.ttf
    - family: faces
      fonts:
        - asset: assets/fonts/FacesPlain.ttf



  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700